name: build
on:
  pull_request:
  push:
    branches: [ rolling ]
  workflow_dispatch:
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 5 * * *'
defaults:
  run:
    shell: bash
jobs:
  build_and_test:
    name: build_and_test_${{ matrix.BUILD_TYPE }}_${{ matrix.ROS_DISTRO }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Rolling (source)
          - ROS_DISTRO: rolling
            BUILD_TYPE: source
            DOCKER_IMAGE: ubuntu:noble
          # Jazzy (binary)
          - ROS_DISTRO: jazzy
            BUILD_TYPE: binary
            DOCKER_IMAGE: ubuntu:noble
          # Iron (binary)
          - ROS_DISTRO: iron
            BUILD_TYPE: binary
            DOCKER_IMAGE: ubuntu:jammy
    env:
      ROS2_REPOS_FILE_URL: 'https://raw.githubusercontent.com/ros2/ros2/${{ matrix.ROS_DISTRO }}/ros2.repos'
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.DOCKER_IMAGE }}
    steps:
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ matrix.BUILD_TYPE == 'binary' && matrix.ROS_DISTRO || ''}}
    - name: Build and run tests
      id: action-ros-ci
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: |
          rmw_zenoh_cpp
          zenoh_c_vendor
        target-ros2-distro: ${{ matrix.ROS_DISTRO }}
        vcs-repo-file-url: ${{ matrix.BUILD_TYPE == 'source' && env.ROS2_REPOS_FILE_URL || '' }}
