name: build
on:
  pull_request:
  push:
    branches: [ rolling ]
  workflow_dispatch:
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 5 * * *'
defaults:
  run:
    shell: bash
jobs:
  build_and_test:
      name: build_and_test ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
      strategy:
        matrix:
          ROS_DISTRO: [rolling, jazzy, iron]
          ROS_REPO: [testing, main]
      runs-on: ubuntu-latest
      container:
        image: rostooling/setup-ros-docker:ubuntu-noble-latest
      steps:
      - name: Build and run tests
        id: action-ros-ci
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            rmw_zenoh_cpp
            zenoh_c_vendor
          target-ros2-distro: ${{ matrix.ROS_DISTRO }}
          vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/rolling/ros2.repos
